server:
  port: 8081

spring:
  application:
    name: springboot-leakybucket-ratelimiter

rate-limiter:
  leaky-bucket:
    enabled: true
    capacity: 10
    leak-rate-per-second: 2.0
    key-type: IP               # IP | HEADER
    header-name: X-Api-Key     # used if key-type=HEADER
    include-headers: true      # add X-RateLimit-* headers
